# Generated by Django 4.2.16 on 2024-11-08 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NganhTuyenSinh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_nganh', models.CharField(max_length=100)),
                ('ten_nganh', models.CharField(max_length=255)),
                ('mo_ta', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'nganh_tuyen_sinh',
            },
        ),
    ]
