# Generated by Django 4.2.16 on 2024-12-20 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_caudieukien'),
    ]

    operations = [
        migrations.AddField(
            model_name='caudieukien',
            name='example',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='caudieukien',
            name='recipe',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='caudieukien',
            name='theuse',
            field=models.TextField(blank=True, null=True),
        ),
    ]
